apiVersion: v1
kind: Secret
metadata:
  name: proudcity
type: Opaque
data:
  gcserviceaccount.json: bm90aGluZw==
  stateless-media-bucket: ZmVpZGVybmQ=
  stateless-media-account: c3RvcmFnZUBwcm91ZGNpdHktMTE4NC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbQ==